/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { AppSettings } from '../types';

export const generateESP32Ino = (settings: AppSettings): string => {
  const { hardware, brightness } = settings;
  const armsCount = hardware.armsCount || 2;
  
  // Dynamically declare ARM pin definitions
  let armPinsDef = `#define ARM_COUNT ${armsCount}\n#define ARM1_PIN ${hardware.arm1Pin}\n`;
  if (armsCount > 1) {
    armPinsDef += `#define ARM2_PIN ${hardware.arm2Pin}\n`;
  }
  if (armsCount > 2) {
    armPinsDef += `#define ARM3_PIN ${hardware.arm3Pin}\n`;
  }
  if (armsCount > 3) {
    armPinsDef += `#define ARM4_PIN ${hardware.arm4Pin}\n`;
  }

  // Dynamically declare FastLED setup calls
  let fastLedAddLeds = `  FastLED.addLeds<WS2812B, ARM1_PIN, GRB>(leds[0], LED_COUNT);\n`;
  if (armsCount > 1) {
    fastLedAddLeds += `  FastLED.addLeds<WS2812B, ARM2_PIN, GRB>(leds[1], LED_COUNT);\n`;
  }
  if (armsCount > 2) {
    fastLedAddLeds += `  FastLED.addLeds<WS2812B, ARM3_PIN, GRB>(leds[2], LED_COUNT);\n`;
  }
  if (armsCount > 3) {
    fastLedAddLeds += `  FastLED.addLeds<WS2812B, ARM4_PIN, GRB>(leds[3], LED_COUNT);\n`;
  }

  return `/**
 * HOLOSPIN X - Production POV Hologram OS
 * Generated by Aether OS
 * Target: ESP32-WROOM-32
 */

#include <FastLED.h>
#include <WiFi.h>
#include <WiFiManager.h>
#include <ESPAsyncWebServer.h>
#include <WebSocketsServer.h>
#include <ArduinoJson.h>
#include <Update.h>
#include <SPI.h>
#include <SD.h>

// HARDWARE CONFIG
#define LED_COUNT ${hardware.ledCount}
#define BRIGHTNESS ${brightness}

// ARM CONFIG & PINS
${armPinsDef}
// SENSORS & STORAGE
#define HALL_PIN ${hardware.hallPin}
#define SD_CS ${hardware.sdCs}
#define SD_MOSI ${hardware.sdMosi}
#define SD_MISO ${hardware.sdMiso}
#define SD_SCK ${hardware.sdSck}
#define AUDIO_PIN 35

// FASTLED ARRAYS
CRGB leds[ARM_COUNT][LED_COUNT];

// NETWORK
const char* ssid = "HOLOSPIN_X";
const char* password = "12345678";
AsyncWebServer server(80);
WebSocketsServer webSocket = WebSocketsServer(81);

// POV ENGINE STATE
volatile unsigned long lastHallTrigger = 0;
volatile unsigned long currentRPM = 0;
volatile unsigned long frameTime = 0;
volatile bool syncPulse = false;

// EFFECT STATE
String currentEffect = "matrix";
uint8_t globalBrightness = BRIGHTNESS;

// POV LOGIC
#define SECTORS 90
uint16_t frameBuffer[SECTORS][LED_COUNT]; // Using RGB565 for memory efficiency
uint16_t currentSector = 0;

void IRAM_ATTR hallSensorInterrupt() {
  unsigned long now = micros();
  unsigned long diff = now - lastHallTrigger;
  if(diff > 10000) { // Debounce > 10ms (max ~6000 RPM)
    currentRPM = 60000000 / diff;
    frameTime = diff;
    lastHallTrigger = now;
    syncPulse = true;
  }
}

void setup() {
  Serial.begin(${hardware.baudRate});
  
  // LED Setup
${fastLedAddLeds}  FastLED.setBrightness(globalBrightness);
  FastLED.clear();
  FastLED.show();

  // Hall Sensor
  pinMode(HALL_PIN, INPUT_PULLUP);
  attachInterrupt(digitalPinToInterrupt(HALL_PIN), hallSensorInterrupt, FALLING);

  // SD Setup
  SPI.begin(SD_SCK, SD_MISO, SD_MOSI, SD_CS);
  if(!SD.begin(SD_CS)) {
    Serial.println("SD WARNING: Card mount failed");
  } else {
    Serial.println("SD Ready");
  }

  // WiFi Setup
  WiFiManager wm;
  
  // Set custom AP settings
  wm.setAPCallback([](WiFiManager *myWiFiManager) {
    Serial.println("Entered config mode");
    Serial.println(WiFi.softAPIP());
    Serial.println(myWiFiManager->getConfigPortalSSID());
  });

  if (!wm.autoConnect(ssid, password)) {
    Serial.println("Failed to connect and hit timeout");
    delay(3000);
    ESP.restart();
  }

  Serial.println("WiFi Connected!");
  Serial.print("IP Address: ");
  Serial.println(WiFi.localIP());

  // Web Server - OTA Update Route
  server.on("/", HTTP_GET, [](AsyncWebServerRequest *request){
    request->send(200, "text/html", "<h1>HOLOSPIN X OTA SERVER</h1><form method='POST' action='/update' enctype='multipart/form-data'><input type='file' name='update'><input type='submit' value='Update'></form>");
  });
  
  server.on("/update", HTTP_POST, [](AsyncWebServerRequest *request){
    bool shouldReboot = !Update.hasError();
    AsyncWebServerResponse *response = request->beginResponse(200, "text/plain", shouldReboot ? "OK" : "FAIL");
    response->addHeader("Connection", "close");
    request->send(response);
  }, [](AsyncWebServerRequest *request, String filename, size_t index, uint8_t *data, size_t len, bool final){
    if(!index){
      Serial.printf("Update Start: %s\\n", filename.c_str());
      if(!Update.begin((ESP.getFreeSketchSpace() - 0x1000) & 0xFFFFF000)){
        Update.printError(Serial);
      }
    }
    if(!Update.hasError()){
      if(Update.write(data, len) != len){
        Update.printError(Serial);
      }
    }
    if(final){
      if(Update.end(true)){
        Serial.printf("Update Success: %uB\\n", index+len);
      } else {
        Update.printError(Serial);
      }
    }
  });
  server.begin();

  // WebSocket Setup
  webSocket.begin();
  webSocket.onEvent(webSocketEvent);
  
  Serial.println("HOLOSPIN X BOOT COMPLETE");
}

void renderPOV() {
  if (syncPulse) {
    syncPulse = false;
    currentSector = 0;
  }
  
  unsigned long timeSinceHall = micros() - lastHallTrigger;
  unsigned long sectorTime = frameTime / SECTORS;
  
  // Predict current sector based on elapsed time
  if (sectorTime > 0) {
    uint16_t calculatedSector = timeSinceHall / sectorTime;
    if (calculatedSector < SECTORS) {
      currentSector = calculatedSector;
    }
  }

  // Map buffer to dynamic active arms (distributed symmetrically)
  for(int arm = 0; arm < ARM_COUNT; arm++) {
    int s = (currentSector + (arm * (SECTORS / ARM_COUNT))) % SECTORS;
    for(int i = 0; i < LED_COUNT; i++) {
       // Convert RGB565 to CRGB
       uint16_t c = frameBuffer[s][i];
       uint8_t r = (c >> 11) << 3;
       uint8_t g = ((c >> 5) & 0x3F) << 2;
       uint8_t b = (c & 0x1F) << 3;
       leds[arm][i] = CRGB(r,g,b);
    }
  }
  
  FastLED.show();
}

// Simulated Effects
void fxMatrix() {
  // basic green rain logic on frameBuffer internally
}
void fxSpectrum() {
  int audio = analogRead(AUDIO_PIN);
  // audio reactive logic
}

void loop() {
  webSocket.loop();
  
  // Real-time POV rendering
  if (currentRPM > 100) {
    renderPOV();
  } else {
    // idle spin or show static effects on arms
    FastLED.show();
  }
  
  // Telemetry loop
  static unsigned long lastTelemetry = 0;
  if(millis() - lastTelemetry > 1000) {
    lastTelemetry = millis();
    broadcastTelemetry();
  }
}

void broadcastTelemetry() {
  StaticJsonDocument<256> doc;
  doc["rpm"] = currentRPM;
  doc["fps"] = (currentRPM * SECTORS) / 60; // Approximate render FPS
  doc["wifi"] = WiFi.RSSI();
  doc["temperature"] = temperatureRead();
  doc["effect"] = currentEffect;
  
  String out;
  serializeJson(doc, out);
  webSocket.broadcastTXT(out);
}

void webSocketEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t length) {
  if (type == WStype_TEXT) {
    StaticJsonDocument<512> doc;
    DeserializationError error = deserializeJson(doc, payload);
    if (error) return;
    
    if (doc.containsKey("cmd")) {
      String cmd = doc["cmd"].as<String>();
      if (cmd == "effect") {
        currentEffect = doc["name"].as<String>();
      } else if (cmd == "brightness") {
        globalBrightness = doc["value"].as<int>();
        FastLED.setBrightness(globalBrightness);
      } else if (cmd == "gif") {
        // trigger gif sequence loading
      } else if (cmd == "ota") {
        // handle ota prep
      } else if (cmd == "wifi") {
        String newSsid = doc["ssid"].as<String>();
        String newPass = doc["password"].as<String>();
        WiFi.begin(newSsid.c_str(), newPass.c_str());
      }
    }
  }
}
`;
};

