[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
lib_deps =
    fastled/FastLED @ ^3.6.0
    bblanchon/ArduinoJson @ ^6.21.3
    me-no-dev/ESP Async WebServer @ ^1.2.3
    me-no-dev/AsyncTCP @ ^1.1.1
    https://github.com/Links2004/arduinoWebSockets.git
    FS
    SPI
    SD
